### ISSUE TITLE
Ao enviar POST tip com dados {} (sem tip), causa 500 Internal Server Error

### ISSUE THREAD

**Issue by rafaelclp** [uiansol/lol-counter#11]
Deveria causar um 400 Bad Request ao enviar um body com {} para POST /api/champion/:id/tip.

Ao invés disso, causa 500 Internal Server Error. Stack trace:
Traceback (most recent call last):
  File "tornado/web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "server.py", line 88, in post
    tip = json.loads(self.request.body.decode('utf-8'))['tip']
KeyError: 'tip'

Ao enviar um body vazio funciona sem problema.

Passei mais de meia hora achando que eu estava implementado errado os testes porque funcionava no Advanced Rest Client, mas... "{}" quebra, "" não =P.

**Comment by rafaelclp** [comment]
Corrigido. Agora eu verifico se a chave "tip" existe. Do jeito que tinha sido antes, só quebrava se não conseguia converter para utf8 ou não conseguia carregar o json (json.loads).
